name: improved_initiative_interceptor
description: An absolute bare-bones web app.
version: 1.0.1

environment:
  sdk: ^3.5.0

dependencies:
  lzma: ^1.0.1
  messagepack: ^0.2.1

dev_dependencies:
  build_runner: ^2.4.12
  build_web_compilers: ^4.0.11
  custom_lint: ^0.6.5
  dart_test_tools: ">=5.11.7 <7.0.0"
  webdev: ^3.6.0
