name: improved_initiative_interceptor
description: An absolute bare-bones web app.
version: 2.0.0

environment:
  sdk: ^3.7.0

dependencies:
  lzstring: ^2.0.0+2
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.1
  custom_lint: ">=0.7.3 <0.9.0"
  dart_test_tools: ^6.1.0
  webdev: ^3.7.1
